package registration.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "user")
public class AppUser {

    @DynamoDBHashKey
    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String mobileNumber;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private String role;

}