amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    region: us-east-1
    accesskey: dummyid
    secretkey: dummypw
server:
  port: 9999
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: addrestaurant-route-id
          uri: lb://addrestaurant
          filters:
            - RoleAuth=ADMIN
          predicates:
            - Path=/food/api/v1/admin/add-restaurant/**
        - id: updateprice-route-id
          uri: lb://updateprice
          filters:
            - RoleAuth=ADMIN
          predicates:
            - Path=/food/api/v1/admin/update-price/**
        - id: registration-route-id
          uri: lb://registration
          predicates:
            - Path=/food/api/v1/user/register/
        - id: login-route-id
          uri: lb://registration
          predicates:
            - Path=/food/api/v1/user/login/**
        - id: search-route-id
          uri: lb://searchfood
          filters:
            - RoleAuth=CUSTOMER
          predicates:
            - Path=/food/api/v1/user/restaurantname/**
        - id: search-route-id
          uri: lb://searchfood
#          filters:
#            - RoleAuth=CUSTOMER
          predicates:
            - Path=/food/api/v1/user/menuitem/**
#  main:
#    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost