# Amazon DynamoDB, AWS configuration
amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    region: us-east-1
    accesskey: dummyid
    secretkey: dummypw

# Server port configuration
server:
  port: 9002

# Spring application name
spring:
  application:
    name: addrestaurant

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

# RabbitMQ configuration
rabbitmq:
  exchange:
    name: restaurant_exchange
  queue:
    json:
      name: restaurant_json
  routing:
    json:
      key: restaurant_routing_json_key
