# Configuration for Amazon DynamoDB
amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    region: us-east-1
    accesskey: dummyid
    secretkey: dummypw

# Server configuration
server:
  port: 9004

# Spring application configuration
spring:
  application:
    name: searchfood

# Feign client configuration
feign:
  circuitbreaker:
    enabled: true

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
