amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    region: us-east-1
    accesskey: dummyid
    secretkey: dummypw
server:
  port: 9004
spring:
  application:
    name: searchfood
#  cloud:
#    openfeign:
#      circuitbreaker:
#        enabled: true
#        alphanumeric-ids:
#          enabled: true
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        baseConfig:
#          fallbackEnabled: true
feign:
  circuitbreaker:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost